export const headingIconText = {

    // home page 
    aboutUs__IconText : "About Us",
    basementRenovations__IconText : "Basement Renovations",
    experienced__IconText : "Experienced",
    professional__IconText : "Professional",
    expert__IconText : "Expert, Well Equipped",
    elevating__IconText : "Elevating",
    trusted__IconText : "Trusted",
    readyToStart__IconText : "Ready to Start",
    faq__IconText : "FAQ",
    workingProcess__IconText : "Working Process",
    gallery__IconText : "Gallery",
    chooseUs__IconText : "Choose Us",
    serviceAreas__IconText : "Service Areas",
    ourBasementRenovation__IconText : "Do's and Don'ts", 
    benefits__IconText : "Benefits",
    review__IconText : "Reviews",
    contactNow__IconText : "Contact Now",
    contactUs__IconText : "Get Consultant",
    considerationAndLimitation__IconText : "Consideration & Limitation",

    // Basement Walkout in Toronto page 
    aboutUs__IconText : "About Us",
    expertContractors__IconText : "Expert Contractors",
    definitionOfWalkoutBasement__IconText : "Definition of Walkout Basement",
    addBasementWalkout__IconText : "Add Basement Walkout",
    services__IconText : "Services",
    gallery__IconText : "Gallery",
    cost__IconText : "Cost",
    underpinning__IconText : "Underpinning",
    benefits__IconText : "Benefits",
    prosAndCons__IconText : "Pros and Cons",
    Reviews__IconText : "Reviews",
    chooseUs__IconText : "Choose Us",
    faq__IconText : "FAQ",
    serviceAreas__IconText : "Service Areas",
    getConsultant__IconText : "Get Consultant",
    contactNow__IconText : "Contact Now",

}